module.exports = [
    {
      "projID": "sittris",
      "number": 1,
      "name": "Sittris",
      "heading": "Healthcare Seating System",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "cuisipro",
      "number": 2,
      "name": "Cuisipro",
      "heading": "Kitchen Collection",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "revo",
      "number": 3,
      "name": "Revo",
      "heading": "Performance Sunglasses",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "roka",
      "number": 4,
      "name": "Roka",
      "heading": "Performance Eyewear",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "xdclaymore",
      "number": 5,
      "name": "xd claymore",
      "heading": "Angled Barbell Exercise Unit",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "bangerz",
      "number": 6,
      "name": "Bangerz",
      "heading": "Women’s Field Sport Goggle",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "gs",
      "number": 7,
      "name": "gs",
      "heading": "Flatware Collection",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "switch-vision",
      "number": 8,
      "name": "Switch Vision",
      "heading": "Magnetic Interchange Lens System",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "+1",
      "number": 9,
      "name": "+1",
      "heading": "Condom Case",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "thermos",
      "number": 10,
      "name": "Thermos",
      "heading": "Cooler Bags",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
    {
      "projID": "foldinglawnchair",
      "number": 11,
      "name": "Folding Lawn Chair",
      "heading": "specialty eyewear",
      "description": "",
      "image": "https://i.imgur.com/3WPEmCJ.jpeg",
      "carousel-img1": "",
      "carousel-img2": "",
      "carousel-img3": "",
      "carousel-blurb1": "",
      "carousel-blurb2": "",
      "carousel-blurb3": "",
      
    },
]
