module.exports = [
    {
      "projID": "sittris",
      "projNUM": 1,
      "number": "01",
      "name": "Sittris",
      "heading": "Healthcare Seating System",
      "description": "Clean seating that stays clean. The Sittris line was designed specifically for the healthcare environment, addressing such issues as infection control, patient diversity, and worker health and safety.",
      "image": "../../home-feature-images/1.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Sittris_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_Sittris_2.png",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C101",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C102",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C103",
      }],
    },
    {
      "projID": "+1",
      "projNUM": 2,
      "number": "02",
      "name": "+1",
      "heading": "Condom Case",
      "description": "Single piece polypropylene case designed for the incentives market.",
      "image": "../../home-feature-images/2.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_CondomCase_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_CondomCase_2.png",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C201",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C202",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C203",
      }],
    },
    {
      "projID": "roka",
      "projNUM": 3,
      "number": "03",
      "name": "Roka",
      "heading": "Performance Eyewear",
      "description": "Having established themselves a strong place in the triathalon market, Roka was looking to expand their catalogue into eyewear. The collection combines classic shapes with the performance features of modern sport frames, creating a unique crossbreed of stylish sport sunglasses.",
      "image": "../../home-feature-images/3.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Roka_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_Roka_2.png",
        "id": 2,
      },
      {
        "image":"../../project-images/Feature_Roka_3.png",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C301",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C302",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C303",
      }],
    },
    {
      "projID": "switch-vision",
      "projNUM": 4,
      "number": "04",
      "name": "Switch Vision",
      "heading": "Magnetic Interchange System",
      "description": "Switch utilizes neodymium magnets embedded in the lens and frame, allowing fast and simple exchange of lenses to adapt to changing light conditions. The line has evolved with each new frame, pushing the limits of the technology.",
      "image": "../../home-feature-images/4.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Switch_1.png",
        "id": 1,
      },
      {
        "image":" ",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C401",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C402",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C403",
      }],
    },
    {
      "projID": "rideconcepts",
      "projNUM": 5,
      "number": "05",
      "name": "Ride Concepts",
      "heading": "Mountain Bike Footwear",
      "description": "Technically driven mountain bike specific footwear, tailored for men, women, and youth. Materials, fabrication, and styling all adhere to this technology driven identity. The outsoles are comprised of a proprietary rubber compound, offering optimal grip, durability, and comfort.",
      "image": "../../home-feature-images/5.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_RideConcepts_1.png",
        "id": 1,
      },
      {
        "image":" ",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C501",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C502",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C503",
      }],
    },
    {
      "projID": "gourmet-settings",
      "projNUM": 6,
      "number": "06",
      "name": "Gourmet Settings",
      "heading": "Flatware Collection",
      "description": "Contemporary stainless steel flatware, designed to look and feel great at an affordable price. Complete brand maintenance from the design of the flatware itself, to packaging, in-store merchandising, and tradeshow presence.",
      "image": "../../home-feature-images/6.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_GourmetSettings_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_GourmetSettings_2.png",
        "id": 2,
      },
      {
        "image":"../../project-images/Feature_GourmetSettings_3.png",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C601",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C602",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C603",
      }],
    },
    {
      "projID": "revo",
      "projNUM": 7,
      "number": "07",
      "name": "Revo",
      "heading": "Performance Sunglasses",
      "description": "Under new ownership, Revo was looking to breathe new life into the brand and needed to quickly fill out their line. The collection consists of new sport performance frames to compliment the existing Core lineup, as well as a new Heritage line of fashion/lifestyle frames.",
      "image": "../../home-feature-images/7.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Revo_1_adjusted.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_Revo_2.png",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Inspired by the silhouette and edge banding of the Gibson Les Paul guitar, a new injection process was utilized to achieve this unique look.",
        "key":"C701",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C702",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C703",
      }],
    },
    {
      "projID": "xdclaymore",
      "projNUM": 8,
      "number": "08",
      "name": "XD Claymore",
      "heading": "Angled Barbell Exercise Unit",
      "description": "Conceived as a compact and lightweight solution to the Landmine exercise unit, the Claymore was developed in house and licensed to XD Fitness. This patented design can be positioned at any point along a wall to act as an anchor for an angled barbell. Patent No. US20170189737A1",
      "image": "../../home-feature-images/8.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Claymore_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_Claymore_2.png",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C801",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C802",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C803",
      }],
    },
    {
      "projID": "revant",
      "projNUM": 9,
      "number": "09",
      "name": "Revant",
      "heading": "Performance Sunglasses",
      "description": "Revant wanted to introduce their own line of sport performance eyewear to compliment their existing lens replacement business. In keeping with their company DNA, all parts of the frame can be easily removed and replaced.",
      "image": "../../home-feature-images/9.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Revant_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_Revant_2.png",
        "id": 2,
      },
      {
        "image":"../../project-images/Feature_Revant_3.png",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C901",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C902",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C903",
      }],
    },
    {
      "projID": "cuisipro",
      "projNUM": 10,
      "number": "10",
      "name": "Cuisipro",
      "heading": "Kitchen Collection",
      "description": "Tools for Cooks. Functional innovation and ergonomic design are combined to create a distinct brand identity for Cuisipro. The collection encompasses a broad range of kitchen implements, tied together with a common aesthetic and focus on performance.",
      "image": "../../home-feature-images/10.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Cuisipro_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_Cuisipro_2.png",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C1001",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C1002",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C1003",
      }],
    },
    {
      "projID": "foldinglawnchair",
      "projNUM": 11,
      "number": "11",
      "name": "Folding Lawn Chair",
      "heading": "",
      "description": "Inspired by the folding aluminum chairs popularized in the 1950’s, this conceptual design utilizes the latest materials and manufacturing techniques to bring new life to this iconic object.",
      "image": "../../home-feature-images/12.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_FoldingChair_1.png",
        "id": 1,
      },
      {
        "image":" ",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C1101",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C1102",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C1103",
      }],
    },
    {
      "projID": "thermos",
      "projNUM": 12,
      "number": "12",
      "name": "Thermos",
      "heading": "Cooler Bags",
      "description": "Simple, functional cooler bags designed for the entry level market. Divided compartments allow for separation of hot and cold items.",
      "image": "../../home-feature-images/13.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Thermos_1.png",
        "id": 1,
      },
      {
        "image":" ",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C1201",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C1202",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C1203",
      }],
    },
    {
      "projID": "bangerz",
      "projNUM": 13,
      "number": "13",
      "name": "Women’s Field Sport Goggle",
      "heading": "specialty eyewear",
      "description": "Utilizing a new permanent anti-fog lens, the Elite was designed to maximize field of vision while still withstanding the rigours of women’s field sports that require high impact testing. Designed to meet both ASTM F803-03 for lacrosse, and ASTM F2713-14 for field hockey.",
      "image": "../../home-feature-images/14.png",
      "alt": "need to add text here",
      "featureImage": [{
        "image":"../../project-images/Feature_Bangerz_1.png",
        "id": 1,
      },
      {
        "image":"../../project-images/Feature_Bangerz_2.png",
        "id": 2,
      },
      {
        "image":" ",
        "id": 3,
      }],
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
        "key":"C1301",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
        "key":"C1302",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
        "key":"C1303",
      }],
    },
]
