module.exports = [
    {
      "projID": "sittris",
      "projNUM": 1,
      "number": "01",
      "name": "Sittris",
      "heading": "Healthcare Seating System",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/1.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "cuisipro",
      "projNUM": 2,
      "number": "02",
      "name": "Cuisipro",
      "heading": "Kitchen Collection",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/2.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "revo",
      "projNUM": 3,
      "number": "03",
      "name": "Revo",
      "heading": "Performance Sunglasses",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/3.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "roka",
      "projNUM": 4,
      "number": "04",
      "name": "Roka",
      "heading": "Performance Eyewear",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/4.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "xdclaymore",
      "projNUM": 5,
      "number": "05",
      "name": "xd claymore",
      "heading": "Angled Barbell Exercise Unit",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/5.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "bangerz",
      "projNUM": 6,
      "number": "06",
      "name": "Bangerz",
      "heading": "Women’s Field Sport Goggle",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/6.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "gs",
      "projNUM": 7,
      "number": "07",
      "name": "gs",
      "heading": "Flatware Collection",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/7.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "switch-vision",
      "projNUM": 8,
      "number": "08",
      "name": "Switch Vision",
      "heading": "Magnetic Interchange Lens System",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/8.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "+1",
      "projNUM": 9,
      "number": "09",
      "name": "+1",
      "heading": "Condom Case",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/9.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "thermos",
      "projNUM": 10,
      "number": "10",
      "name": "Thermos",
      "heading": "Cooler Bags",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/10.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "foldinglawnchair",
      "projNUM": 11,
      "number": "11",
      "name": "Folding Lawn Chair",
      "heading": "specialty eyewear",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/11.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "foldinglawnchair",
      "projNUM": 12,
      "number": "12",
      "name": "Folding Lawn Chair",
      "heading": "specialty eyewear",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/12.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "foldinglawnchair",
      "projNUM": 13,
      "number": "13",
      "name": "Folding Lawn Chair",
      "heading": "specialty eyewear",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/13.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "foldinglawnchair",
      "projNUM": 14,
      "number": "14",
      "name": "Folding Lawn Chair",
      "heading": "specialty eyewear",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/14.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "foldinglawnchair",
      "projNUM": 15,
      "number": "15",
      "name": "Folding Lawn Chair",
      "heading": "specialty eyewear",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/15.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    {
      "projID": "foldinglawnchair",
      "projNUM": 16,
      "number": "16",
      "name": "Folding Lawn Chair",
      "heading": "specialty eyewear",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
      "image": "../../home-feature-images/16.png",
      "alt": "need to add text here",
      "featureImage": "../../stock_PlaceholderImage.png",
      "displaySlide": {
        "slide": "../../slide1.png",
        "frameNum": "1",
      },
      "carousel": [{
        "slide": "../../slide1.png",
        "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
      },
      {
        "slide": "../../slide2.png",
        "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
      },
      {
        "slide": "../../slide3.png",
        "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
      }],
    },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 17,
    //   "number": "17",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/12.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 18,
    //   "number": "18",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/13.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 19,
    //   "number": "19",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/14.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 20,
    //   "number": "20",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/15.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 21,
    //   "number": "21",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/16a.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 22,
    //   "number": "22",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/16b.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 23,
    //   "number": "23",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/17.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 24,
    //   "number": "24",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/18.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 25,
    //   "number": "25",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/19.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 26,
    //   "number": "26",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/20.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 27,
    //   "number": "27",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/21a.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 28,
    //   "number": "28",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/21b.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 29,
    //   "number": "29",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/22.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
    // {
    //   "projID": "foldinglawnchair",
    //   "projNUM": 30,
    //   "number": "30",
    //   "name": "Folding Lawn Chair",
    //   "heading": "specialty eyewear",
    //   "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup.",
    //   "image": "../../feature-images/23.png",
    //   "featureImage": "../../stock_PlaceholderImage.png",
    //   "displaySlide": {
    //     "slide": "../../slide1.png",
    //     "frameNum": "1",
    //   },
    //   "carousel": [{
    //     "slide": "../../slide1.png",
    //     "blurb":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini.",
    //   },
    //   {
    //     "slide": "../../slide2.png",
    //     "blurb":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh.",
    //   },
    //   {
    //     "slide": "../../slide3.png",
    //     "blurb":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no.",
    //   }],
    // },
]
