module.exports = [
  {
    "projID": "sittris",
    "projNUM": 1,
    "id": 200,
    "image": "../../home-feature-images/1.png",
    "alt": "need to add text here",
  },
  {
    "projID": "+1",
    "projNUM": 2,
    "id": 201,
    "image": "../../home-feature-images/2.png",
    "alt": "need to add text here",
  },
  {
    "projID": "roka",
    "projNUM": 3,
    "id": 202,
    "image": "../../home-feature-images/3.png",
    "alt": "need to add text here",
  },
  {
    "projID": "switch-vision",
    "projNUM": 4,
    "id": 203,
    "image": "../../home-feature-images/4.png",
    "alt": "need to add text here",
  },
  {
    "projID": "rideconcepts",
    "projNUM": 5,
    "id": 204,
    "image": "../../home-feature-images/5.png",
    "alt": "need to add text here",
  },
  {
    "projID": "gourmet-settings",
    "projNUM": 6,
    "id": 205,
    "image": "../../home-feature-images/6.png",
    "alt": "need to add text here",
  },
  {
    "projID": "revo",
    "projNUM": 7,
    "id": 206,
    "image": "../../home-feature-images/7.png",
    "alt": "need to add text here",
  },
  {
    "projID": "xdclaymore",
    "projNUM": 8,
    "id": 207,
    "image": "../../home-feature-images/8.png",
    "alt": "need to add text here",
  },
  {
    "projID": "revant",
    "projNUM": 9,
    "id": 208,
    "image": "../../home-feature-images/9.png",
    "alt": "need to add text here",
  },
  {
    "projID": "cuisipro",
    "projNUM": 10,
    "id": 209,
    "image": "../../home-feature-images/10.png",
    "alt": "need to add text here",
  },
  {
    "projID": "rideconcepts",
    "projNUM": 11,
    "id": 210,
    "image": "../../home-feature-images/11.png",
    "alt": "need to add text here",
  },
  {
    "projID": "foldinglawnchair",
    "projNUM": 12,
    "id": 211,
    "image": "../../home-feature-images/12.png",
    "alt": "need to add text here",
  },
  {
    "projID": "thermos",
    "projNUM": 13,
    "id": 212,
    "image": "../../home-feature-images/13.png",
    "alt": "need to add text here",
  },
  {
    "projID": "bangerz",
    "projNUM": 14,
    "id": 213,
    "image": "../../home-feature-images/14.png",
    "alt": "need to add text here",
  },
  {
    "projID": "roka",
    "projNUM": 15,
    "id": 214,
    "image": "../../home-feature-images/15.png",
    "alt": "need to add text here",
  },
  {
    "projID": "cuisipro",
    "projNUM": 16,
    "id": 215,
    "image": "../../home-feature-images/16.png",
    "alt": "need to add text here",
  },
]
